<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>LeipzigCraft-Launcher</AssemblyName>
    <RootNamespace>LeipzigCraft.Launcher</RootNamespace>

    <Version>0.1.0</Version>
    <FileVersion>0.1.0.0</FileVersion>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core" Version="4.0.6" />
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
    <PackageReference Include="fNbt" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\leipzigcraft-logo.png" />
  </ItemGroup>

</Project>
